version: '3'
services:
  mysql:
    image: mysql:5.7.37
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dSSALHwSsCiXzPr
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
      - TZ=Asia/Shanghai
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
